// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: wizard_system.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace WizardSystem.Protobuf {
  public static partial class WizardService
  {
    static readonly string __ServiceName = "WizardSystem.WizardService";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::WizardSystem.Protobuf.Image> __Marshaller_WizardSystem_Image = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WizardSystem.Protobuf.Image.Parser));
    static readonly grpc::Marshaller<global::WizardSystem.Protobuf.Magic> __Marshaller_WizardSystem_Magic = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WizardSystem.Protobuf.Magic.Parser));

    static readonly grpc::Method<global::WizardSystem.Protobuf.Image, global::WizardSystem.Protobuf.Magic> __Method_PostMagicImageRaw = new grpc::Method<global::WizardSystem.Protobuf.Image, global::WizardSystem.Protobuf.Magic>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PostMagicImageRaw",
        __Marshaller_WizardSystem_Image,
        __Marshaller_WizardSystem_Magic);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::WizardSystem.Protobuf.WizardSystemReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of WizardService</summary>
    [grpc::BindServiceMethod(typeof(WizardService), "BindService")]
    public abstract partial class WizardServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::WizardSystem.Protobuf.Magic> PostMagicImageRaw(global::WizardSystem.Protobuf.Image request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for WizardService</summary>
    public partial class WizardServiceClient : grpc::ClientBase<WizardServiceClient>
    {
      /// <summary>Creates a new client for WizardService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public WizardServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for WizardService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public WizardServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected WizardServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected WizardServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::WizardSystem.Protobuf.Magic PostMagicImageRaw(global::WizardSystem.Protobuf.Image request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PostMagicImageRaw(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::WizardSystem.Protobuf.Magic PostMagicImageRaw(global::WizardSystem.Protobuf.Image request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_PostMagicImageRaw, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::WizardSystem.Protobuf.Magic> PostMagicImageRawAsync(global::WizardSystem.Protobuf.Image request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PostMagicImageRawAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::WizardSystem.Protobuf.Magic> PostMagicImageRawAsync(global::WizardSystem.Protobuf.Image request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_PostMagicImageRaw, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override WizardServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new WizardServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(WizardServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PostMagicImageRaw, serviceImpl.PostMagicImageRaw).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, WizardServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PostMagicImageRaw, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::WizardSystem.Protobuf.Image, global::WizardSystem.Protobuf.Magic>(serviceImpl.PostMagicImageRaw));
    }

  }
}
#endregion
